sudo: required
services:
  - docker
  
before_install:
  - docker build -t urmel-80/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true urmel-80/react-app npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-016154154267"
  bucket_path: "Docker"  
  on:
    branch: master
    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
